# fly.toml app configuration file generated for repo-exercise-little-snowflake-7106 on 2025-02-24T18:30:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'repo-exercise-little-snowflake-7106'
primary_region = 'atl'

[build]

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
