POST http://localhost:80/api/notes
Content-Type: application/json

{
    "id": "4",
    "content": "Try backend"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "NOK",
    "important": false
}